/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSettingSettingsKeyGet200,
  HTTPValidationError,
  ListSettingsSettingsGet200Item,
  ListSettingsSettingsGetParams,
  SettingUpdate,
  UpdateSettingSettingsKeyPut200
} from '../../model';

import { customFetch } from '../../client';
import type { ErrorType , BodyType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Settings
 */
export type listSettingsSettingsGetResponse200 = {
  data: ListSettingsSettingsGet200Item[]
  status: 200
}

export type listSettingsSettingsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listSettingsSettingsGetResponseSuccess = (listSettingsSettingsGetResponse200) & {
  headers: Headers;
};
export type listSettingsSettingsGetResponseError = (listSettingsSettingsGetResponse422) & {
  headers: Headers;
};

export type listSettingsSettingsGetResponse = (listSettingsSettingsGetResponseSuccess | listSettingsSettingsGetResponseError)

export const getListSettingsSettingsGetUrl = (params?: ListSettingsSettingsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/settings?${stringifiedParams}` : `/settings`
}

export const listSettingsSettingsGet = async (params?: ListSettingsSettingsGetParams, options?: RequestInit): Promise<listSettingsSettingsGetResponse> => {
  
  return customFetch<listSettingsSettingsGetResponse>(getListSettingsSettingsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListSettingsSettingsGetQueryKey = (params?: ListSettingsSettingsGetParams,) => {
    return [
    `/settings`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListSettingsSettingsGetQueryOptions = <TData = Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError = ErrorType<HTTPValidationError>>(params?: ListSettingsSettingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSettingsSettingsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSettingsSettingsGet>>> = ({ signal }) => listSettingsSettingsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSettingsSettingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSettingsSettingsGet>>>
export type ListSettingsSettingsGetQueryError = ErrorType<HTTPValidationError>


export function useListSettingsSettingsGet<TData = Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListSettingsSettingsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSettingsSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof listSettingsSettingsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSettingsSettingsGet<TData = Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListSettingsSettingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSettingsSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof listSettingsSettingsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSettingsSettingsGet<TData = Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListSettingsSettingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Settings
 */

export function useListSettingsSettingsGet<TData = Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListSettingsSettingsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSettingsSettingsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSettingsSettingsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Setting
 */
export type getSettingSettingsKeyGetResponse200 = {
  data: GetSettingSettingsKeyGet200
  status: 200
}

export type getSettingSettingsKeyGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSettingSettingsKeyGetResponseSuccess = (getSettingSettingsKeyGetResponse200) & {
  headers: Headers;
};
export type getSettingSettingsKeyGetResponseError = (getSettingSettingsKeyGetResponse422) & {
  headers: Headers;
};

export type getSettingSettingsKeyGetResponse = (getSettingSettingsKeyGetResponseSuccess | getSettingSettingsKeyGetResponseError)

export const getGetSettingSettingsKeyGetUrl = (key: string,) => {


  

  return `/settings/${key}`
}

export const getSettingSettingsKeyGet = async (key: string, options?: RequestInit): Promise<getSettingSettingsKeyGetResponse> => {
  
  return customFetch<getSettingSettingsKeyGetResponse>(getGetSettingSettingsKeyGetUrl(key),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetSettingSettingsKeyGetQueryKey = (key: string,) => {
    return [
    `/settings/${key}`
    ] as const;
    }

    
export const getGetSettingSettingsKeyGetQueryOptions = <TData = Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError = ErrorType<HTTPValidationError>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingSettingsKeyGetQueryKey(key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>> = ({ signal }) => getSettingSettingsKeyGet(key, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(key), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingSettingsKeyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>>
export type GetSettingSettingsKeyGetQueryError = ErrorType<HTTPValidationError>


export function useGetSettingSettingsKeyGet<TData = Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError = ErrorType<HTTPValidationError>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettingSettingsKeyGet>>,
          TError,
          Awaited<ReturnType<typeof getSettingSettingsKeyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettingSettingsKeyGet<TData = Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError = ErrorType<HTTPValidationError>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettingSettingsKeyGet>>,
          TError,
          Awaited<ReturnType<typeof getSettingSettingsKeyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettingSettingsKeyGet<TData = Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError = ErrorType<HTTPValidationError>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Setting
 */

export function useGetSettingSettingsKeyGet<TData = Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError = ErrorType<HTTPValidationError>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettingSettingsKeyGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingSettingsKeyGetQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Setting
 */
export type updateSettingSettingsKeyPutResponse200 = {
  data: UpdateSettingSettingsKeyPut200
  status: 200
}

export type updateSettingSettingsKeyPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateSettingSettingsKeyPutResponseSuccess = (updateSettingSettingsKeyPutResponse200) & {
  headers: Headers;
};
export type updateSettingSettingsKeyPutResponseError = (updateSettingSettingsKeyPutResponse422) & {
  headers: Headers;
};

export type updateSettingSettingsKeyPutResponse = (updateSettingSettingsKeyPutResponseSuccess | updateSettingSettingsKeyPutResponseError)

export const getUpdateSettingSettingsKeyPutUrl = (key: string,) => {


  

  return `/settings/${key}`
}

export const updateSettingSettingsKeyPut = async (key: string,
    settingUpdate: SettingUpdate, options?: RequestInit): Promise<updateSettingSettingsKeyPutResponse> => {
  
  return customFetch<updateSettingSettingsKeyPutResponse>(getUpdateSettingSettingsKeyPutUrl(key),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      settingUpdate,)
  }
);}
  



export const getUpdateSettingSettingsKeyPutMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingSettingsKeyPut>>, TError,{key: string;data: BodyType<SettingUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSettingSettingsKeyPut>>, TError,{key: string;data: BodyType<SettingUpdate>}, TContext> => {

const mutationKey = ['updateSettingSettingsKeyPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSettingSettingsKeyPut>>, {key: string;data: BodyType<SettingUpdate>}> = (props) => {
          const {key,data} = props ?? {};

          return  updateSettingSettingsKeyPut(key,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSettingSettingsKeyPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateSettingSettingsKeyPut>>>
    export type UpdateSettingSettingsKeyPutMutationBody = BodyType<SettingUpdate>
    export type UpdateSettingSettingsKeyPutMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Setting
 */
export const useUpdateSettingSettingsKeyPut = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingSettingsKeyPut>>, TError,{key: string;data: BodyType<SettingUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSettingSettingsKeyPut>>,
        TError,
        {key: string;data: BodyType<SettingUpdate>},
        TContext
      > => {
      return useMutation(getUpdateSettingSettingsKeyPutMutationOptions(options), queryClient);
    }
    