/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */

export type HardDeleteBusinessesHardDeletePost200 = { [key: string]: unknown };
