/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */

export interface RunRequest {
  place_ids: string[];
  model?: string | null;
  test_model?: string | null;
  max_fix_iterations?: number | null;
  no_email?: boolean;
  playwright?: boolean;
}
