/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */

export interface SearchRequest {
  location: string;
  query: string;
  types?: string[];
  limit?: number;
  min_score?: number;
  grid_size?: number;
}
