/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */
import type { ValidationErrorCtx } from './validationErrorCtx';

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}
