"""Port interfaces — abstract protocols for persistence and file storage."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from webseed.models import BusinessData, BusinessRecord, PipelineEvent, PipelineStatus


class PersistencePort(Protocol):
    """Abstract persistence interface for business data and settings."""

    # Business CRUD
    def upsert_business(self, biz: BusinessData, run_id: str) -> str: ...
    def find_by_place_id(self, place_id: str) -> BusinessRecord | None: ...
    def find_by_name(self, query: str) -> list[BusinessRecord]: ...
    def resolve_identifier(self, identifier: str) -> list[BusinessRecord]: ...
    def update_status(self, place_id: str, status: PipelineStatus, extra: dict[str, Any] | None = None) -> bool: ...
    def delete_business(self, place_id: str) -> bool: ...
    def all_place_ids(self) -> set[str]: ...
    def get_all_businesses(self, status: str | None = None) -> list[BusinessRecord]: ...

    # Blacklist
    def get_blacklisted_place_ids(self) -> set[str]: ...

    # Settings (prompts + config)
    def get_setting(self, key: str) -> str | None: ...
    def upsert_setting(self, key: str, value: str, description: str = "") -> None: ...
    def list_settings(self, prefix: str | None = None) -> list[dict[str, Any]]: ...
    def delete_setting(self, key: str) -> bool: ...

    # Crash recovery
    def reset_stale_running(self) -> int: ...

    # Event logging
    def log_event(self, job_id: str, place_id: str, event_type: str, step: str, message: str, data: dict[str, Any]) -> None: ...


class FileStoragePort(Protocol):
    """Abstract file storage interface."""

    def site_dir(self, name_slug: str) -> str: ...
    def photo_dir(self, name_slug: str) -> str: ...
    def screenshots_dir(self) -> str: ...
    def write_file(self, relative_path: str, content: str | bytes) -> str: ...
    def read_file(self, relative_path: str) -> str: ...
    def exists(self, relative_path: str) -> bool: ...
    def list_files(self, relative_path: str, pattern: str = "*") -> list[str]: ...
    def delete_dir(self, relative_path: str) -> None: ...


# Event callback type alias
EventCallback = Callable[[PipelineEvent], None]
