/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BlacklistAddBusinessesPlaceIdBlacklistPost200,
  BlacklistRemoveBusinessesPlaceIdBlacklistDelete200,
  CloseBusinessesBusinessesClosePost200,
  CloseRequest,
  DeleteBusinessBusinessesPlaceIdDelete200,
  GetBusinessBusinessesPlaceIdGet200,
  GetStatsBusinessesStatsGet200,
  HTTPValidationError,
  HardDeleteBusinessesHardDeletePost200,
  HardDeleteRequest,
  ListBusinessesBusinessesGet200Item,
  ListBusinessesBusinessesGetParams,
  StatusUpdate,
  UpdateStatusBusinessesPlaceIdStatusPatch200
} from '../../model';

import { customFetch } from '../../client';
import type { ErrorType , BodyType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Businesses
 */
export type listBusinessesBusinessesGetResponse200 = {
  data: ListBusinessesBusinessesGet200Item[]
  status: 200
}

export type listBusinessesBusinessesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listBusinessesBusinessesGetResponseSuccess = (listBusinessesBusinessesGetResponse200) & {
  headers: Headers;
};
export type listBusinessesBusinessesGetResponseError = (listBusinessesBusinessesGetResponse422) & {
  headers: Headers;
};

export type listBusinessesBusinessesGetResponse = (listBusinessesBusinessesGetResponseSuccess | listBusinessesBusinessesGetResponseError)

export const getListBusinessesBusinessesGetUrl = (params?: ListBusinessesBusinessesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/businesses?${stringifiedParams}` : `/businesses`
}

export const listBusinessesBusinessesGet = async (params?: ListBusinessesBusinessesGetParams, options?: RequestInit): Promise<listBusinessesBusinessesGetResponse> => {
  
  return customFetch<listBusinessesBusinessesGetResponse>(getListBusinessesBusinessesGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getListBusinessesBusinessesGetQueryKey = (params?: ListBusinessesBusinessesGetParams,) => {
    return [
    `/businesses`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListBusinessesBusinessesGetQueryOptions = <TData = Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError = ErrorType<HTTPValidationError>>(params?: ListBusinessesBusinessesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBusinessesBusinessesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>> = ({ signal }) => listBusinessesBusinessesGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBusinessesBusinessesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>>
export type ListBusinessesBusinessesGetQueryError = ErrorType<HTTPValidationError>


export function useListBusinessesBusinessesGet<TData = Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListBusinessesBusinessesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBusinessesBusinessesGet>>,
          TError,
          Awaited<ReturnType<typeof listBusinessesBusinessesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBusinessesBusinessesGet<TData = Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListBusinessesBusinessesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBusinessesBusinessesGet>>,
          TError,
          Awaited<ReturnType<typeof listBusinessesBusinessesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBusinessesBusinessesGet<TData = Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListBusinessesBusinessesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Businesses
 */

export function useListBusinessesBusinessesGet<TData = Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListBusinessesBusinessesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBusinessesBusinessesGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBusinessesBusinessesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Stats
 */
export type getStatsBusinessesStatsGetResponse200 = {
  data: GetStatsBusinessesStatsGet200
  status: 200
}

export type getStatsBusinessesStatsGetResponseSuccess = (getStatsBusinessesStatsGetResponse200) & {
  headers: Headers;
};
;

export type getStatsBusinessesStatsGetResponse = (getStatsBusinessesStatsGetResponseSuccess)

export const getGetStatsBusinessesStatsGetUrl = () => {


  

  return `/businesses/stats`
}

export const getStatsBusinessesStatsGet = async ( options?: RequestInit): Promise<getStatsBusinessesStatsGetResponse> => {
  
  return customFetch<getStatsBusinessesStatsGetResponse>(getGetStatsBusinessesStatsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetStatsBusinessesStatsGetQueryKey = () => {
    return [
    `/businesses/stats`
    ] as const;
    }

    
export const getGetStatsBusinessesStatsGetQueryOptions = <TData = Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatsBusinessesStatsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>> = ({ signal }) => getStatsBusinessesStatsGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatsBusinessesStatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>>
export type GetStatsBusinessesStatsGetQueryError = ErrorType<unknown>


export function useGetStatsBusinessesStatsGet<TData = Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatsBusinessesStatsGet<TData = Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatsBusinessesStatsGet<TData = Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Stats
 */

export function useGetStatsBusinessesStatsGet<TData = Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsBusinessesStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatsBusinessesStatsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Export Csv
 */
export type exportCsvBusinessesExportCsvGetResponse200 = {
  data: unknown
  status: 200
}

export type exportCsvBusinessesExportCsvGetResponseSuccess = (exportCsvBusinessesExportCsvGetResponse200) & {
  headers: Headers;
};
;

export type exportCsvBusinessesExportCsvGetResponse = (exportCsvBusinessesExportCsvGetResponseSuccess)

export const getExportCsvBusinessesExportCsvGetUrl = () => {


  

  return `/businesses/export/csv`
}

export const exportCsvBusinessesExportCsvGet = async ( options?: RequestInit): Promise<exportCsvBusinessesExportCsvGetResponse> => {
  
  return customFetch<exportCsvBusinessesExportCsvGetResponse>(getExportCsvBusinessesExportCsvGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getExportCsvBusinessesExportCsvGetQueryKey = () => {
    return [
    `/businesses/export/csv`
    ] as const;
    }

    
export const getExportCsvBusinessesExportCsvGetQueryOptions = <TData = Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportCsvBusinessesExportCsvGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>> = ({ signal }) => exportCsvBusinessesExportCsvGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportCsvBusinessesExportCsvGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>>
export type ExportCsvBusinessesExportCsvGetQueryError = ErrorType<unknown>


export function useExportCsvBusinessesExportCsvGet<TData = Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>,
          TError,
          Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportCsvBusinessesExportCsvGet<TData = Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>,
          TError,
          Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportCsvBusinessesExportCsvGet<TData = Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Csv
 */

export function useExportCsvBusinessesExportCsvGet<TData = Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportCsvBusinessesExportCsvGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportCsvBusinessesExportCsvGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Business
 */
export type getBusinessBusinessesPlaceIdGetResponse200 = {
  data: GetBusinessBusinessesPlaceIdGet200
  status: 200
}

export type getBusinessBusinessesPlaceIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getBusinessBusinessesPlaceIdGetResponseSuccess = (getBusinessBusinessesPlaceIdGetResponse200) & {
  headers: Headers;
};
export type getBusinessBusinessesPlaceIdGetResponseError = (getBusinessBusinessesPlaceIdGetResponse422) & {
  headers: Headers;
};

export type getBusinessBusinessesPlaceIdGetResponse = (getBusinessBusinessesPlaceIdGetResponseSuccess | getBusinessBusinessesPlaceIdGetResponseError)

export const getGetBusinessBusinessesPlaceIdGetUrl = (placeId: string,) => {


  

  return `/businesses/${placeId}`
}

export const getBusinessBusinessesPlaceIdGet = async (placeId: string, options?: RequestInit): Promise<getBusinessBusinessesPlaceIdGetResponse> => {
  
  return customFetch<getBusinessBusinessesPlaceIdGetResponse>(getGetBusinessBusinessesPlaceIdGetUrl(placeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetBusinessBusinessesPlaceIdGetQueryKey = (placeId: string,) => {
    return [
    `/businesses/${placeId}`
    ] as const;
    }

    
export const getGetBusinessBusinessesPlaceIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError = ErrorType<HTTPValidationError>>(placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBusinessBusinessesPlaceIdGetQueryKey(placeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>> = ({ signal }) => getBusinessBusinessesPlaceIdGet(placeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(placeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBusinessBusinessesPlaceIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>>
export type GetBusinessBusinessesPlaceIdGetQueryError = ErrorType<HTTPValidationError>


export function useGetBusinessBusinessesPlaceIdGet<TData = Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError = ErrorType<HTTPValidationError>>(
 placeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBusinessBusinessesPlaceIdGet<TData = Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError = ErrorType<HTTPValidationError>>(
 placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBusinessBusinessesPlaceIdGet<TData = Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError = ErrorType<HTTPValidationError>>(
 placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Business
 */

export function useGetBusinessBusinessesPlaceIdGet<TData = Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError = ErrorType<HTTPValidationError>>(
 placeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBusinessBusinessesPlaceIdGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBusinessBusinessesPlaceIdGetQueryOptions(placeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete Business
 */
export type deleteBusinessBusinessesPlaceIdDeleteResponse200 = {
  data: DeleteBusinessBusinessesPlaceIdDelete200
  status: 200
}

export type deleteBusinessBusinessesPlaceIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteBusinessBusinessesPlaceIdDeleteResponseSuccess = (deleteBusinessBusinessesPlaceIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteBusinessBusinessesPlaceIdDeleteResponseError = (deleteBusinessBusinessesPlaceIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteBusinessBusinessesPlaceIdDeleteResponse = (deleteBusinessBusinessesPlaceIdDeleteResponseSuccess | deleteBusinessBusinessesPlaceIdDeleteResponseError)

export const getDeleteBusinessBusinessesPlaceIdDeleteUrl = (placeId: string,) => {


  

  return `/businesses/${placeId}`
}

export const deleteBusinessBusinessesPlaceIdDelete = async (placeId: string, options?: RequestInit): Promise<deleteBusinessBusinessesPlaceIdDeleteResponse> => {
  
  return customFetch<deleteBusinessBusinessesPlaceIdDeleteResponse>(getDeleteBusinessBusinessesPlaceIdDeleteUrl(placeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteBusinessBusinessesPlaceIdDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBusinessBusinessesPlaceIdDelete>>, TError,{placeId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBusinessBusinessesPlaceIdDelete>>, TError,{placeId: string}, TContext> => {

const mutationKey = ['deleteBusinessBusinessesPlaceIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBusinessBusinessesPlaceIdDelete>>, {placeId: string}> = (props) => {
          const {placeId} = props ?? {};

          return  deleteBusinessBusinessesPlaceIdDelete(placeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBusinessBusinessesPlaceIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBusinessBusinessesPlaceIdDelete>>>
    
    export type DeleteBusinessBusinessesPlaceIdDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Business
 */
export const useDeleteBusinessBusinessesPlaceIdDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBusinessBusinessesPlaceIdDelete>>, TError,{placeId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBusinessBusinessesPlaceIdDelete>>,
        TError,
        {placeId: string},
        TContext
      > => {
      return useMutation(getDeleteBusinessBusinessesPlaceIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Status
 */
export type updateStatusBusinessesPlaceIdStatusPatchResponse200 = {
  data: UpdateStatusBusinessesPlaceIdStatusPatch200
  status: 200
}

export type updateStatusBusinessesPlaceIdStatusPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateStatusBusinessesPlaceIdStatusPatchResponseSuccess = (updateStatusBusinessesPlaceIdStatusPatchResponse200) & {
  headers: Headers;
};
export type updateStatusBusinessesPlaceIdStatusPatchResponseError = (updateStatusBusinessesPlaceIdStatusPatchResponse422) & {
  headers: Headers;
};

export type updateStatusBusinessesPlaceIdStatusPatchResponse = (updateStatusBusinessesPlaceIdStatusPatchResponseSuccess | updateStatusBusinessesPlaceIdStatusPatchResponseError)

export const getUpdateStatusBusinessesPlaceIdStatusPatchUrl = (placeId: string,) => {


  

  return `/businesses/${placeId}/status`
}

export const updateStatusBusinessesPlaceIdStatusPatch = async (placeId: string,
    statusUpdate: StatusUpdate, options?: RequestInit): Promise<updateStatusBusinessesPlaceIdStatusPatchResponse> => {
  
  return customFetch<updateStatusBusinessesPlaceIdStatusPatchResponse>(getUpdateStatusBusinessesPlaceIdStatusPatchUrl(placeId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      statusUpdate,)
  }
);}
  



export const getUpdateStatusBusinessesPlaceIdStatusPatchMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatusBusinessesPlaceIdStatusPatch>>, TError,{placeId: string;data: BodyType<StatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStatusBusinessesPlaceIdStatusPatch>>, TError,{placeId: string;data: BodyType<StatusUpdate>}, TContext> => {

const mutationKey = ['updateStatusBusinessesPlaceIdStatusPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStatusBusinessesPlaceIdStatusPatch>>, {placeId: string;data: BodyType<StatusUpdate>}> = (props) => {
          const {placeId,data} = props ?? {};

          return  updateStatusBusinessesPlaceIdStatusPatch(placeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStatusBusinessesPlaceIdStatusPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateStatusBusinessesPlaceIdStatusPatch>>>
    export type UpdateStatusBusinessesPlaceIdStatusPatchMutationBody = BodyType<StatusUpdate>
    export type UpdateStatusBusinessesPlaceIdStatusPatchMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Status
 */
export const useUpdateStatusBusinessesPlaceIdStatusPatch = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatusBusinessesPlaceIdStatusPatch>>, TError,{placeId: string;data: BodyType<StatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStatusBusinessesPlaceIdStatusPatch>>,
        TError,
        {placeId: string;data: BodyType<StatusUpdate>},
        TContext
      > => {
      return useMutation(getUpdateStatusBusinessesPlaceIdStatusPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Blacklist Add
 */
export type blacklistAddBusinessesPlaceIdBlacklistPostResponse200 = {
  data: BlacklistAddBusinessesPlaceIdBlacklistPost200
  status: 200
}

export type blacklistAddBusinessesPlaceIdBlacklistPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type blacklistAddBusinessesPlaceIdBlacklistPostResponseSuccess = (blacklistAddBusinessesPlaceIdBlacklistPostResponse200) & {
  headers: Headers;
};
export type blacklistAddBusinessesPlaceIdBlacklistPostResponseError = (blacklistAddBusinessesPlaceIdBlacklistPostResponse422) & {
  headers: Headers;
};

export type blacklistAddBusinessesPlaceIdBlacklistPostResponse = (blacklistAddBusinessesPlaceIdBlacklistPostResponseSuccess | blacklistAddBusinessesPlaceIdBlacklistPostResponseError)

export const getBlacklistAddBusinessesPlaceIdBlacklistPostUrl = (placeId: string,) => {


  

  return `/businesses/${placeId}/blacklist`
}

export const blacklistAddBusinessesPlaceIdBlacklistPost = async (placeId: string, options?: RequestInit): Promise<blacklistAddBusinessesPlaceIdBlacklistPostResponse> => {
  
  return customFetch<blacklistAddBusinessesPlaceIdBlacklistPostResponse>(getBlacklistAddBusinessesPlaceIdBlacklistPostUrl(placeId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getBlacklistAddBusinessesPlaceIdBlacklistPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blacklistAddBusinessesPlaceIdBlacklistPost>>, TError,{placeId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof blacklistAddBusinessesPlaceIdBlacklistPost>>, TError,{placeId: string}, TContext> => {

const mutationKey = ['blacklistAddBusinessesPlaceIdBlacklistPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blacklistAddBusinessesPlaceIdBlacklistPost>>, {placeId: string}> = (props) => {
          const {placeId} = props ?? {};

          return  blacklistAddBusinessesPlaceIdBlacklistPost(placeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BlacklistAddBusinessesPlaceIdBlacklistPostMutationResult = NonNullable<Awaited<ReturnType<typeof blacklistAddBusinessesPlaceIdBlacklistPost>>>
    
    export type BlacklistAddBusinessesPlaceIdBlacklistPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Blacklist Add
 */
export const useBlacklistAddBusinessesPlaceIdBlacklistPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blacklistAddBusinessesPlaceIdBlacklistPost>>, TError,{placeId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blacklistAddBusinessesPlaceIdBlacklistPost>>,
        TError,
        {placeId: string},
        TContext
      > => {
      return useMutation(getBlacklistAddBusinessesPlaceIdBlacklistPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Blacklist Remove
 */
export type blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse200 = {
  data: BlacklistRemoveBusinessesPlaceIdBlacklistDelete200
  status: 200
}

export type blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponseSuccess = (blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse200) & {
  headers: Headers;
};
export type blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponseError = (blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse422) & {
  headers: Headers;
};

export type blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse = (blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponseSuccess | blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponseError)

export const getBlacklistRemoveBusinessesPlaceIdBlacklistDeleteUrl = (placeId: string,) => {


  

  return `/businesses/${placeId}/blacklist`
}

export const blacklistRemoveBusinessesPlaceIdBlacklistDelete = async (placeId: string, options?: RequestInit): Promise<blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse> => {
  
  return customFetch<blacklistRemoveBusinessesPlaceIdBlacklistDeleteResponse>(getBlacklistRemoveBusinessesPlaceIdBlacklistDeleteUrl(placeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getBlacklistRemoveBusinessesPlaceIdBlacklistDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blacklistRemoveBusinessesPlaceIdBlacklistDelete>>, TError,{placeId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof blacklistRemoveBusinessesPlaceIdBlacklistDelete>>, TError,{placeId: string}, TContext> => {

const mutationKey = ['blacklistRemoveBusinessesPlaceIdBlacklistDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blacklistRemoveBusinessesPlaceIdBlacklistDelete>>, {placeId: string}> = (props) => {
          const {placeId} = props ?? {};

          return  blacklistRemoveBusinessesPlaceIdBlacklistDelete(placeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BlacklistRemoveBusinessesPlaceIdBlacklistDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof blacklistRemoveBusinessesPlaceIdBlacklistDelete>>>
    
    export type BlacklistRemoveBusinessesPlaceIdBlacklistDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Blacklist Remove
 */
export const useBlacklistRemoveBusinessesPlaceIdBlacklistDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blacklistRemoveBusinessesPlaceIdBlacklistDelete>>, TError,{placeId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blacklistRemoveBusinessesPlaceIdBlacklistDelete>>,
        TError,
        {placeId: string},
        TContext
      > => {
      return useMutation(getBlacklistRemoveBusinessesPlaceIdBlacklistDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Hard Delete
 */
export type hardDeleteBusinessesHardDeletePostResponse200 = {
  data: HardDeleteBusinessesHardDeletePost200
  status: 200
}

export type hardDeleteBusinessesHardDeletePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type hardDeleteBusinessesHardDeletePostResponseSuccess = (hardDeleteBusinessesHardDeletePostResponse200) & {
  headers: Headers;
};
export type hardDeleteBusinessesHardDeletePostResponseError = (hardDeleteBusinessesHardDeletePostResponse422) & {
  headers: Headers;
};

export type hardDeleteBusinessesHardDeletePostResponse = (hardDeleteBusinessesHardDeletePostResponseSuccess | hardDeleteBusinessesHardDeletePostResponseError)

export const getHardDeleteBusinessesHardDeletePostUrl = () => {


  

  return `/businesses/hard-delete`
}

export const hardDeleteBusinessesHardDeletePost = async (hardDeleteRequest: HardDeleteRequest, options?: RequestInit): Promise<hardDeleteBusinessesHardDeletePostResponse> => {
  
  return customFetch<hardDeleteBusinessesHardDeletePostResponse>(getHardDeleteBusinessesHardDeletePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      hardDeleteRequest,)
  }
);}
  



export const getHardDeleteBusinessesHardDeletePostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hardDeleteBusinessesHardDeletePost>>, TError,{data: BodyType<HardDeleteRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof hardDeleteBusinessesHardDeletePost>>, TError,{data: BodyType<HardDeleteRequest>}, TContext> => {

const mutationKey = ['hardDeleteBusinessesHardDeletePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof hardDeleteBusinessesHardDeletePost>>, {data: BodyType<HardDeleteRequest>}> = (props) => {
          const {data} = props ?? {};

          return  hardDeleteBusinessesHardDeletePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type HardDeleteBusinessesHardDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof hardDeleteBusinessesHardDeletePost>>>
    export type HardDeleteBusinessesHardDeletePostMutationBody = BodyType<HardDeleteRequest>
    export type HardDeleteBusinessesHardDeletePostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Hard Delete
 */
export const useHardDeleteBusinessesHardDeletePost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hardDeleteBusinessesHardDeletePost>>, TError,{data: BodyType<HardDeleteRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof hardDeleteBusinessesHardDeletePost>>,
        TError,
        {data: BodyType<HardDeleteRequest>},
        TContext
      > => {
      return useMutation(getHardDeleteBusinessesHardDeletePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Close Businesses
 */
export type closeBusinessesBusinessesClosePostResponse200 = {
  data: CloseBusinessesBusinessesClosePost200
  status: 200
}

export type closeBusinessesBusinessesClosePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type closeBusinessesBusinessesClosePostResponseSuccess = (closeBusinessesBusinessesClosePostResponse200) & {
  headers: Headers;
};
export type closeBusinessesBusinessesClosePostResponseError = (closeBusinessesBusinessesClosePostResponse422) & {
  headers: Headers;
};

export type closeBusinessesBusinessesClosePostResponse = (closeBusinessesBusinessesClosePostResponseSuccess | closeBusinessesBusinessesClosePostResponseError)

export const getCloseBusinessesBusinessesClosePostUrl = () => {


  

  return `/businesses/close`
}

export const closeBusinessesBusinessesClosePost = async (closeRequest: CloseRequest, options?: RequestInit): Promise<closeBusinessesBusinessesClosePostResponse> => {
  
  return customFetch<closeBusinessesBusinessesClosePostResponse>(getCloseBusinessesBusinessesClosePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      closeRequest,)
  }
);}
  



export const getCloseBusinessesBusinessesClosePostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeBusinessesBusinessesClosePost>>, TError,{data: BodyType<CloseRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof closeBusinessesBusinessesClosePost>>, TError,{data: BodyType<CloseRequest>}, TContext> => {

const mutationKey = ['closeBusinessesBusinessesClosePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeBusinessesBusinessesClosePost>>, {data: BodyType<CloseRequest>}> = (props) => {
          const {data} = props ?? {};

          return  closeBusinessesBusinessesClosePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CloseBusinessesBusinessesClosePostMutationResult = NonNullable<Awaited<ReturnType<typeof closeBusinessesBusinessesClosePost>>>
    export type CloseBusinessesBusinessesClosePostMutationBody = BodyType<CloseRequest>
    export type CloseBusinessesBusinessesClosePostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Close Businesses
 */
export const useCloseBusinessesBusinessesClosePost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeBusinessesBusinessesClosePost>>, TError,{data: BodyType<CloseRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeBusinessesBusinessesClosePost>>,
        TError,
        {data: BodyType<CloseRequest>},
        TContext
      > => {
      return useMutation(getCloseBusinessesBusinessesClosePostMutationOptions(options), queryClient);
    }
    