/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeployRequest,
  EmailRequest,
  EnrichRequest,
  GenerateRequest,
  HTTPValidationError,
  JobResponse,
  RunRequest,
  SearchRequest,
  TestRequest
} from '../../model';

import { customFetch } from '../../client';
import type { ErrorType , BodyType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Pipeline Search
 */
export type pipelineSearchPipelineSearchPostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineSearchPipelineSearchPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineSearchPipelineSearchPostResponseSuccess = (pipelineSearchPipelineSearchPostResponse200) & {
  headers: Headers;
};
export type pipelineSearchPipelineSearchPostResponseError = (pipelineSearchPipelineSearchPostResponse422) & {
  headers: Headers;
};

export type pipelineSearchPipelineSearchPostResponse = (pipelineSearchPipelineSearchPostResponseSuccess | pipelineSearchPipelineSearchPostResponseError)

export const getPipelineSearchPipelineSearchPostUrl = () => {


  

  return `/pipeline/search`
}

export const pipelineSearchPipelineSearchPost = async (searchRequest: SearchRequest, options?: RequestInit): Promise<pipelineSearchPipelineSearchPostResponse> => {
  
  return customFetch<pipelineSearchPipelineSearchPostResponse>(getPipelineSearchPipelineSearchPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      searchRequest,)
  }
);}
  



export const getPipelineSearchPipelineSearchPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineSearchPipelineSearchPost>>, TError,{data: BodyType<SearchRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineSearchPipelineSearchPost>>, TError,{data: BodyType<SearchRequest>}, TContext> => {

const mutationKey = ['pipelineSearchPipelineSearchPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineSearchPipelineSearchPost>>, {data: BodyType<SearchRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineSearchPipelineSearchPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineSearchPipelineSearchPostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineSearchPipelineSearchPost>>>
    export type PipelineSearchPipelineSearchPostMutationBody = BodyType<SearchRequest>
    export type PipelineSearchPipelineSearchPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Search
 */
export const usePipelineSearchPipelineSearchPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineSearchPipelineSearchPost>>, TError,{data: BodyType<SearchRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineSearchPipelineSearchPost>>,
        TError,
        {data: BodyType<SearchRequest>},
        TContext
      > => {
      return useMutation(getPipelineSearchPipelineSearchPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Pipeline Enrich
 */
export type pipelineEnrichPipelineEnrichPostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineEnrichPipelineEnrichPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineEnrichPipelineEnrichPostResponseSuccess = (pipelineEnrichPipelineEnrichPostResponse200) & {
  headers: Headers;
};
export type pipelineEnrichPipelineEnrichPostResponseError = (pipelineEnrichPipelineEnrichPostResponse422) & {
  headers: Headers;
};

export type pipelineEnrichPipelineEnrichPostResponse = (pipelineEnrichPipelineEnrichPostResponseSuccess | pipelineEnrichPipelineEnrichPostResponseError)

export const getPipelineEnrichPipelineEnrichPostUrl = () => {


  

  return `/pipeline/enrich`
}

export const pipelineEnrichPipelineEnrichPost = async (enrichRequest: EnrichRequest, options?: RequestInit): Promise<pipelineEnrichPipelineEnrichPostResponse> => {
  
  return customFetch<pipelineEnrichPipelineEnrichPostResponse>(getPipelineEnrichPipelineEnrichPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      enrichRequest,)
  }
);}
  



export const getPipelineEnrichPipelineEnrichPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineEnrichPipelineEnrichPost>>, TError,{data: BodyType<EnrichRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineEnrichPipelineEnrichPost>>, TError,{data: BodyType<EnrichRequest>}, TContext> => {

const mutationKey = ['pipelineEnrichPipelineEnrichPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineEnrichPipelineEnrichPost>>, {data: BodyType<EnrichRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineEnrichPipelineEnrichPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineEnrichPipelineEnrichPostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineEnrichPipelineEnrichPost>>>
    export type PipelineEnrichPipelineEnrichPostMutationBody = BodyType<EnrichRequest>
    export type PipelineEnrichPipelineEnrichPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Enrich
 */
export const usePipelineEnrichPipelineEnrichPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineEnrichPipelineEnrichPost>>, TError,{data: BodyType<EnrichRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineEnrichPipelineEnrichPost>>,
        TError,
        {data: BodyType<EnrichRequest>},
        TContext
      > => {
      return useMutation(getPipelineEnrichPipelineEnrichPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Pipeline Generate
 */
export type pipelineGeneratePipelineGeneratePostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineGeneratePipelineGeneratePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineGeneratePipelineGeneratePostResponseSuccess = (pipelineGeneratePipelineGeneratePostResponse200) & {
  headers: Headers;
};
export type pipelineGeneratePipelineGeneratePostResponseError = (pipelineGeneratePipelineGeneratePostResponse422) & {
  headers: Headers;
};

export type pipelineGeneratePipelineGeneratePostResponse = (pipelineGeneratePipelineGeneratePostResponseSuccess | pipelineGeneratePipelineGeneratePostResponseError)

export const getPipelineGeneratePipelineGeneratePostUrl = () => {


  

  return `/pipeline/generate`
}

export const pipelineGeneratePipelineGeneratePost = async (generateRequest: GenerateRequest, options?: RequestInit): Promise<pipelineGeneratePipelineGeneratePostResponse> => {
  
  return customFetch<pipelineGeneratePipelineGeneratePostResponse>(getPipelineGeneratePipelineGeneratePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateRequest,)
  }
);}
  



export const getPipelineGeneratePipelineGeneratePostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineGeneratePipelineGeneratePost>>, TError,{data: BodyType<GenerateRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineGeneratePipelineGeneratePost>>, TError,{data: BodyType<GenerateRequest>}, TContext> => {

const mutationKey = ['pipelineGeneratePipelineGeneratePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineGeneratePipelineGeneratePost>>, {data: BodyType<GenerateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineGeneratePipelineGeneratePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineGeneratePipelineGeneratePostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineGeneratePipelineGeneratePost>>>
    export type PipelineGeneratePipelineGeneratePostMutationBody = BodyType<GenerateRequest>
    export type PipelineGeneratePipelineGeneratePostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Generate
 */
export const usePipelineGeneratePipelineGeneratePost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineGeneratePipelineGeneratePost>>, TError,{data: BodyType<GenerateRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineGeneratePipelineGeneratePost>>,
        TError,
        {data: BodyType<GenerateRequest>},
        TContext
      > => {
      return useMutation(getPipelineGeneratePipelineGeneratePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Pipeline Test
 */
export type pipelineTestPipelineTestPostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineTestPipelineTestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineTestPipelineTestPostResponseSuccess = (pipelineTestPipelineTestPostResponse200) & {
  headers: Headers;
};
export type pipelineTestPipelineTestPostResponseError = (pipelineTestPipelineTestPostResponse422) & {
  headers: Headers;
};

export type pipelineTestPipelineTestPostResponse = (pipelineTestPipelineTestPostResponseSuccess | pipelineTestPipelineTestPostResponseError)

export const getPipelineTestPipelineTestPostUrl = () => {


  

  return `/pipeline/test`
}

export const pipelineTestPipelineTestPost = async (testRequest: TestRequest, options?: RequestInit): Promise<pipelineTestPipelineTestPostResponse> => {
  
  return customFetch<pipelineTestPipelineTestPostResponse>(getPipelineTestPipelineTestPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      testRequest,)
  }
);}
  



export const getPipelineTestPipelineTestPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineTestPipelineTestPost>>, TError,{data: BodyType<TestRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineTestPipelineTestPost>>, TError,{data: BodyType<TestRequest>}, TContext> => {

const mutationKey = ['pipelineTestPipelineTestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineTestPipelineTestPost>>, {data: BodyType<TestRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineTestPipelineTestPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineTestPipelineTestPostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineTestPipelineTestPost>>>
    export type PipelineTestPipelineTestPostMutationBody = BodyType<TestRequest>
    export type PipelineTestPipelineTestPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Test
 */
export const usePipelineTestPipelineTestPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineTestPipelineTestPost>>, TError,{data: BodyType<TestRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineTestPipelineTestPost>>,
        TError,
        {data: BodyType<TestRequest>},
        TContext
      > => {
      return useMutation(getPipelineTestPipelineTestPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Pipeline Deploy
 */
export type pipelineDeployPipelineDeployPostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineDeployPipelineDeployPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineDeployPipelineDeployPostResponseSuccess = (pipelineDeployPipelineDeployPostResponse200) & {
  headers: Headers;
};
export type pipelineDeployPipelineDeployPostResponseError = (pipelineDeployPipelineDeployPostResponse422) & {
  headers: Headers;
};

export type pipelineDeployPipelineDeployPostResponse = (pipelineDeployPipelineDeployPostResponseSuccess | pipelineDeployPipelineDeployPostResponseError)

export const getPipelineDeployPipelineDeployPostUrl = () => {


  

  return `/pipeline/deploy`
}

export const pipelineDeployPipelineDeployPost = async (deployRequest: DeployRequest, options?: RequestInit): Promise<pipelineDeployPipelineDeployPostResponse> => {
  
  return customFetch<pipelineDeployPipelineDeployPostResponse>(getPipelineDeployPipelineDeployPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deployRequest,)
  }
);}
  



export const getPipelineDeployPipelineDeployPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineDeployPipelineDeployPost>>, TError,{data: BodyType<DeployRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineDeployPipelineDeployPost>>, TError,{data: BodyType<DeployRequest>}, TContext> => {

const mutationKey = ['pipelineDeployPipelineDeployPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineDeployPipelineDeployPost>>, {data: BodyType<DeployRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineDeployPipelineDeployPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineDeployPipelineDeployPostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineDeployPipelineDeployPost>>>
    export type PipelineDeployPipelineDeployPostMutationBody = BodyType<DeployRequest>
    export type PipelineDeployPipelineDeployPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Deploy
 */
export const usePipelineDeployPipelineDeployPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineDeployPipelineDeployPost>>, TError,{data: BodyType<DeployRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineDeployPipelineDeployPost>>,
        TError,
        {data: BodyType<DeployRequest>},
        TContext
      > => {
      return useMutation(getPipelineDeployPipelineDeployPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Pipeline Email
 */
export type pipelineEmailPipelineEmailPostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineEmailPipelineEmailPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineEmailPipelineEmailPostResponseSuccess = (pipelineEmailPipelineEmailPostResponse200) & {
  headers: Headers;
};
export type pipelineEmailPipelineEmailPostResponseError = (pipelineEmailPipelineEmailPostResponse422) & {
  headers: Headers;
};

export type pipelineEmailPipelineEmailPostResponse = (pipelineEmailPipelineEmailPostResponseSuccess | pipelineEmailPipelineEmailPostResponseError)

export const getPipelineEmailPipelineEmailPostUrl = () => {


  

  return `/pipeline/email`
}

export const pipelineEmailPipelineEmailPost = async (emailRequest: EmailRequest, options?: RequestInit): Promise<pipelineEmailPipelineEmailPostResponse> => {
  
  return customFetch<pipelineEmailPipelineEmailPostResponse>(getPipelineEmailPipelineEmailPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailRequest,)
  }
);}
  



export const getPipelineEmailPipelineEmailPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineEmailPipelineEmailPost>>, TError,{data: BodyType<EmailRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineEmailPipelineEmailPost>>, TError,{data: BodyType<EmailRequest>}, TContext> => {

const mutationKey = ['pipelineEmailPipelineEmailPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineEmailPipelineEmailPost>>, {data: BodyType<EmailRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineEmailPipelineEmailPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineEmailPipelineEmailPostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineEmailPipelineEmailPost>>>
    export type PipelineEmailPipelineEmailPostMutationBody = BodyType<EmailRequest>
    export type PipelineEmailPipelineEmailPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Email
 */
export const usePipelineEmailPipelineEmailPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineEmailPipelineEmailPost>>, TError,{data: BodyType<EmailRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineEmailPipelineEmailPost>>,
        TError,
        {data: BodyType<EmailRequest>},
        TContext
      > => {
      return useMutation(getPipelineEmailPipelineEmailPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Pipeline Run
 */
export type pipelineRunPipelineRunPostResponse200 = {
  data: JobResponse
  status: 200
}

export type pipelineRunPipelineRunPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type pipelineRunPipelineRunPostResponseSuccess = (pipelineRunPipelineRunPostResponse200) & {
  headers: Headers;
};
export type pipelineRunPipelineRunPostResponseError = (pipelineRunPipelineRunPostResponse422) & {
  headers: Headers;
};

export type pipelineRunPipelineRunPostResponse = (pipelineRunPipelineRunPostResponseSuccess | pipelineRunPipelineRunPostResponseError)

export const getPipelineRunPipelineRunPostUrl = () => {


  

  return `/pipeline/run`
}

export const pipelineRunPipelineRunPost = async (runRequest: RunRequest, options?: RequestInit): Promise<pipelineRunPipelineRunPostResponse> => {
  
  return customFetch<pipelineRunPipelineRunPostResponse>(getPipelineRunPipelineRunPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      runRequest,)
  }
);}
  



export const getPipelineRunPipelineRunPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineRunPipelineRunPost>>, TError,{data: BodyType<RunRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof pipelineRunPipelineRunPost>>, TError,{data: BodyType<RunRequest>}, TContext> => {

const mutationKey = ['pipelineRunPipelineRunPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelineRunPipelineRunPost>>, {data: BodyType<RunRequest>}> = (props) => {
          const {data} = props ?? {};

          return  pipelineRunPipelineRunPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PipelineRunPipelineRunPostMutationResult = NonNullable<Awaited<ReturnType<typeof pipelineRunPipelineRunPost>>>
    export type PipelineRunPipelineRunPostMutationBody = BodyType<RunRequest>
    export type PipelineRunPipelineRunPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Pipeline Run
 */
export const usePipelineRunPipelineRunPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelineRunPipelineRunPost>>, TError,{data: BodyType<RunRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelineRunPipelineRunPost>>,
        TError,
        {data: BodyType<RunRequest>},
        TContext
      > => {
      return useMutation(getPipelineRunPipelineRunPostMutationOptions(options), queryClient);
    }
    