/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * webseed
 * Automated pipeline for Italian local business website generation
 * OpenAPI spec version: 0.2.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../../client';
import type { ErrorType } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Test Page
 */
export type testPageGetResponse200 = {
  data: string
  status: 200
}

export type testPageGetResponseSuccess = (testPageGetResponse200) & {
  headers: Headers;
};
;

export type testPageGetResponse = (testPageGetResponseSuccess)

export const getTestPageGetUrl = () => {


  

  return `/`
}

export const testPageGet = async ( options?: RequestInit): Promise<testPageGetResponse> => {
  
  return customFetch<testPageGetResponse>(getTestPageGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getTestPageGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getTestPageGetQueryOptions = <TData = Awaited<ReturnType<typeof testPageGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testPageGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTestPageGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof testPageGet>>> = ({ signal }) => testPageGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof testPageGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TestPageGetQueryResult = NonNullable<Awaited<ReturnType<typeof testPageGet>>>
export type TestPageGetQueryError = ErrorType<unknown>


export function useTestPageGet<TData = Awaited<ReturnType<typeof testPageGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof testPageGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof testPageGet>>,
          TError,
          Awaited<ReturnType<typeof testPageGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestPageGet<TData = Awaited<ReturnType<typeof testPageGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testPageGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof testPageGet>>,
          TError,
          Awaited<ReturnType<typeof testPageGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestPageGet<TData = Awaited<ReturnType<typeof testPageGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testPageGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Test Page
 */

export function useTestPageGet<TData = Awaited<ReturnType<typeof testPageGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testPageGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTestPageGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




